# Generated by Django 3.2.4 on 2021-06-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_case_management',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_case_name', models.TextField()),
                ('test_case_preposition', models.TextField()),
                ('test_case_step', models.TextField()),
                ('test_case_expected', models.TextField()),
                ('test_case_results', models.TextField()),
                ('test_case_level', models.TextField()),
                ('test_case_man', models.TextField()),
            ],
        ),
    ]
